'the quick brown fox'
'The New York Times'
'And lo, like wave was he...'
'oops'
'Hello, World!'
'supercalifraglisticexpealadocious'
'On sale for $123.99!!'
'Pi is approximately 3.14159'
'Merge left at the ramp to the right, the restaurant is on the right '
'He said, \"Wait there is more!\"'